language: julia
codecov: true

jobs:
  include:
    - stage: "Testing"
      julia: 1.5.3
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.instantiate()'
        - julia --code-coverage test/mps_test.jl
        - julia --code-coverage test/tebd_test.jl
      after_success:
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
